// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKY55oOYA8BOS3u9Hp-gSD8NxdcNxfunw',
    appId: '1:539096735390:web:368310632b290915b7658f',
    messagingSenderId: '539096735390',
    projectId: 'codeway-case-f2cb8',
    authDomain: 'codeway-case-f2cb8.firebaseapp.com',
    storageBucket: 'codeway-case-f2cb8.appspot.com',
    measurementId: 'G-BLC8PD0XS0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsnjc7qOXEoumGYmPJlPZBMvmDqztjO3s',
    appId: '1:539096735390:android:d196022cc709539fb7658f',
    messagingSenderId: '539096735390',
    projectId: 'codeway-case-f2cb8',
    storageBucket: 'codeway-case-f2cb8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdlOb8w-yTD9zCXSgnzVPvOUhwQtq7gzI',
    appId: '1:539096735390:ios:7fefb420b28830ceb7658f',
    messagingSenderId: '539096735390',
    projectId: 'codeway-case-f2cb8',
    storageBucket: 'codeway-case-f2cb8.appspot.com',
    iosClientId: '539096735390-5bps6u0erk4ji3ntfpcrsc9t2o9fr9f6.apps.googleusercontent.com',
    iosBundleId: 'com.codeway.codewayCase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdlOb8w-yTD9zCXSgnzVPvOUhwQtq7gzI',
    appId: '1:539096735390:ios:7fefb420b28830ceb7658f',
    messagingSenderId: '539096735390',
    projectId: 'codeway-case-f2cb8',
    storageBucket: 'codeway-case-f2cb8.appspot.com',
    iosClientId: '539096735390-5bps6u0erk4ji3ntfpcrsc9t2o9fr9f6.apps.googleusercontent.com',
    iosBundleId: 'com.codeway.codewayCase',
  );
}
